package nure.ua.volonteering_ua.model.user;

public enum SocialCategory {

    PENSIONER,
    PEOPLE_WITH_DISABILITIES,
    ORPHANS_AND_CHILDREN_WITHOUT_PARENTAL_CARE,
    SINGLE_PARENT_FAMILIES,
    LARGE_FAMILIES,
    UNEMPLOYED_PERSONS,
    LOW_INCOME_FAMILIES,
    VICTIMS_OF_DOMESTIC_VIOLENCE,
    HOMELESS_PERSONS,
    REFUGEES_AND_DISPLACED_PERSONS,
    NO_CATEGORY
}

